name: .NET Core CI - Build -> Lint -> Test

on:
  push:
    branches: [ "**" ]  # triggers on push to any branch
  pull_request:
    branches: [ "**" ]  # triggers on pull requests to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up .NET Core SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'  # Set to your .NET version

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the solution
      - name: Build the solution
        run: dotnet build --configuration Release

  lint:
    runs-on: ubuntu-latest
    needs: build  # This makes sure linting happens after the build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'

      - name: Install dotnet-format
        run: dotnet tool install --global dotnet-format

      - name: Run dotnet format check on solution
        run: dotnet format MeChat.sln --check --verbosity diagnostic

      - name: Add StyleCop.Analyzers to all projects
        run: |
          for proj in $(find . -name "*.csproj"); do
            dotnet add "$proj" package StyleCop.Analyzers --version 1.1.0-beta.7
          done

      - name: Run build to trigger StyleCop analyzers
        run: dotnet build MeChat.sln --no-restore --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: lint  # This makes sure tests happen after linting

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up .NET Core SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'  # Adjust if needed

      # Restore the solution
      - name: Restore the solution
        run: dotnet restore test/MeChat.Architecture.Tests/MeChat.Architecture.Tests.csproj

      # Build the test project
      - name: Build the test project
        run: dotnet build test/MeChat.Architecture.Tests/MeChat.Architecture.Tests.csproj --no-restore --configuration Release

      # Run unit tests for MeChat.Architecture.Tests
      - name: Run unit tests for MeChat.Architecture.Tests
        run: dotnet test test/MeChat.Architecture.Tests/MeChat.Architecture.Tests.csproj --no-build --configuration Release --verbosity normal
